FROM python:3.9-slim

WORKDIR /app

COPY server/requirements.txt .

RUN pip install -r requirements.txt

ENV FLASK_RUN_PORT=8000
ENV FLASK_RUN_HOST=0.0.0.0

COPY server/ .

CMD ["flask", "run", "-h", "0.0.0.0", "-p", "8000"]